### ISSUE TITLE
how to save an interactive tree?

### ISSUE THREAD

**Issue by bbest** [mhepner90/RVC#15]
from @mhepner90 ....

Hi Ben,

I have a question regarding what I think involves widgets or javascript. 

I made an interactive tree with my species traits and I can see it in my "viewer" window and can export it is as an html on my local computer but I cant share the html and I can export it as an image but then I loose the interactive components so... do you know how would I save it if I want to include it in a presentation with the interactive components? 

Any advice would be great! Was gonna ask Tylar but he is out on a boat! Lucky him! 

Chunk 4 of [RVC_diversity_analysis.Rmd](https://github.com/mhepner90/RVC/blob/master/RVC_diversity_analysis.Rmd) object 'treemap2'

**Comment by bbest** [comment]
Check out the commit I just made, and open up `htmlwidgets_save.html` to see the presentation or directly here:

https://htmlpreview.github.io/?https://github.com/mhepner90/RVC/blob/master/htmlwidget_save.html

Correction: the above link doesn't properly show interactive widget, but works locally and should when placed in `docs/` as recommended below.

- You need a web browser to display htmlwidgets (which rely on HTML, JS, CSS), so you can use Rmarkdown to create [Presentations with ioslides](http://rmarkdown.rstudio.com/ioslides_presentation_format.html).

- Put the rendered `htmlwidgets_save.html` (and `rendered htmlwidgets_save.html`) in a new `docs/` folder, [turn on Github Pages using docs as Source in your repository's Settings](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages) (requires admin privileges), and you'll be able to publicly view it at https://mhepner90.github.io/RVC/htmlwidget_save.html.

Here's how to save as a static PNG:

```r
# additional libraries
library(htmlwidgets)
library(webshot)

# paths
htm = './htmlwidget_treemap2.html'
png = './htmlwidget_treemap2.png'

# save widget as html
saveWidget(treemap2, htm)

# save widget as png
webshot(htm, png)
```

**Comment by mhepner90** [comment]
Thanks @bbest ! I followed your instructions and now the presentation works https://mhepner90.github.io/RVC/htmlwidget_save.html so thank you!! 

However, I can't seem to edit it. I've made changes to the 'htmlwidgets_save.rmd' and have committed and pushed the changes but I am not actually getting an updated "htmlwidgets_save.html" Am I missing a step for how you created it/converted the rmd to isoslides?? The output in the .rmd file still reads "isoslides_presentation"

**Comment by bbest** [comment]
Are you sure you're updating the `docs/htmlwidget_save.html`? Check the file's [history](https://github.com/mhepner90/RVC/commits/master/docs/htmlwidget_save.html). I strongly recommend moving all htmlwidget_* files into docs/ and editing the Rmd there. When you knit to html it will already be in the correct spot. 

BTW, it's not rendering for me and I see an error in the JavaScript Console:

```
Error: <rect> attribute height: A negative value is not valid. ("-40")
```

![image](https://user-images.githubusercontent.com/2837257/31568212-07a13e98-b028-11e7-89bd-6391294fc65e.png)

**Comment by mhepner90** [comment]
Figured it out! Thanks for all your help! So looking forward to defending next Friday!! 👍 Couldn't have done it without your help! :)

**Comment by bbest** [comment]
Woohoo! Yeah, yeah. Goodluck. You got this :)
