### ISSUE TITLE
populate csv for infographics

### ISSUE THREAD

**Issue by bbest** [mhepner90/RVC#6]
Hi @mhepner90,

Just documenting any issues related to linking to infographics csv here.

**Comment by bbest** [comment]
@mhepner90,

Here's commit f48453a:
- fixed `filter` column SPECIES_CD == "CEP CRUE"
- What does the `group_by` column with values of "protected_status" do?

**Comment by mhepner90** [comment]
I added group_by so that you'd know to plot by level of protection (unprotected, protected) but I still need to talk to Luke to discuss what kind of plots we want.
