### ISSUE TITLE
FD code error, chunk 6

### ISSUE THREAD

**Issue by mhepner90** [mhepner90/RVC#8]
@bbest 

Hi Ben,

I'm still having trouble getting my functional diversity code to run. 

Latest error: #6/12/90 - Error in mutate_impl(.data, dots) : At least one species does not occur in any community (zero total abundance across all communities). 

I tried googling how to fix this and it looks like others have had a similar issue, but I am struggling to resolve the error. 

Would appreciate if you could take a look

**Comment by bbest** [comment]
Hi @mhepner90,

Am playing catch up today, so haven't run the code, but can you try filtering out species without any occurrence first?
